"""Recreate schema with fixes and normalization

Revision ID: 9b68cb1b33ad
Revises: c6ce12d1fc19
Create Date: 2026-05-09 00:05:40.930151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b68cb1b33ad'
down_revision: Union[str, None] = 'c6ce12d1fc19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###